language: node_js
services:
  - docker
sudo: required
node_js:
  - 10.16.1
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
  - docker build . -t "mikeyboom/pmsocspsc:latest"
addons:
  ssh_known_hosts:
    - $SERVER_IP
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - docker login -u=$DOCKER_NAME -p="$DOKCER_PWD"
  - docker push mikeyboom/pmsocspscs:latest
before_install:
  - openssl aes-256-cbc -K $encrypted_1687bb340939_key -iv $encrypted_1687bb340939_iv  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
